version: 0.0
os: linux

files:
  - source: /
    destination: /src/kafka-producer

file_exists_behavior: OVERWRITE

permissions:
  - object: /src/kafka-producer
    owner: ubuntu
    group: ubuntu
    mode: 755