version: 0.0
os: linux

files:
  - source: /
    destination: /src/kafka-producer

file_exists_behavior: OVERWRITE

permissions:
  - object: /src/kafka-producer
    owner: kafka
    group: kafka
    mode: 755

hooks:
  AfterInstall:
    - location: deploy/after_install.sh
      timeout: 120
      runas: kafka